/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App3 {
  public static void main(String[] args) {
    // 기본 출력
    System.out.println("번호: " + 1);
    System.out.println("내용: 게시글입니다.");
    System.out.println("작성일: 2019-01-01");
    System.out.println("조회수: " + 0);
    
    // 문자열 형식을 정의하고 값을 대입해서 출력
    System.out.printf("번호: %d\n", 1);
    System.out.printf("내용: %s\n", "게시글입니다.");
    System.out.printf("작성일: %s\n", "2019-01-01");
    System.out.printf("조회수: %d\n", 1);
  }
}
