/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
  public static void main(String[] args) {
    // 키보드 입력 장치 선언
    java.util.Scanner keyboard = new java.util.Scanner(System.in);
    
    // 입력 받을 내용
    System.out.print("번호? ");
    int num = keyboard.nextInt();
    
    String tmp = keyboard.nextLine();  // LF값을 제거?
    
    System.out.print("수업명? ");
    String className = keyboard.nextLine();
    
    System.out.print("수업내용? ");
    String classContents = keyboard.nextLine();
    
    System.out.print("시작일? ");
    String startDate = keyboard.nextLine();
    
    System.out.print("종료일? ");
    String endDate = keyboard.nextLine();
    
    System.out.print("총수업시간? ");
    int totalTime = keyboard.nextInt();
    
    System.out.print("일수업시간? ");
    int dayTime = keyboard.nextInt();
    
    System.out.println();  // 빈 줄 출력
    
    // 출력할 내용
    System.out.printf("번호: %d\n", num);
    System.out.printf("수업명: %s\n", className);
    System.out.printf("수업내용: %s\n", classContents);
    System.out.printf("기간: %s ~ %s\n", startDate, endDate);
    System.out.printf("총수업시간: %d 시간\n", totalTime);
    System.out.printf("일수업시간: %d 시간\n", dayTime);
    
  }
}
