/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    // 키보드 입력 스트림 (System.in)을 스캐너 객체에 연결한다.
    // => 스캐너는 입력 스트림으로 들어온 문자열을 줄 단위로 잘라주는 역할을 수행한다.
    Scanner keyboard = new Scanner(System.in);

    int length = 10; // 배열 크기
    int[] nums = new int[length];
    String[] titles = new String[length];
    String[] contents = new String[length];
    Date[] startDate = new Date[length];
    Date[] endDate = new Date[length];
    int[] totalTime = new int[length];
    int[] dayTime = new int[length];

    // 입력 받을 내용
    while (true) {
      System.out.print("번호? ");
      // 정수 값 select를 선언해서 입력 받음. 배열의 인덱스 값은 0부터 이므로 -1 해줌.
      int select = Integer.parseInt(keyboard.nextLine())-1;
      nums[select] = select+1; // 첫 번호를 1로 주기 위해 +1 해줌.

      System.out.print("수업명? ");
      titles[select] = keyboard.nextLine();

      System.out.print("수업내용? ");
      contents[select] = keyboard.nextLine();

      System.out.print("시작일? ");
      startDate[select] = Date.valueOf(keyboard.nextLine());

      System.out.print("종료일? ");
      endDate[select] = Date.valueOf(keyboard.nextLine());

      System.out.print("총수업시간? ");
      totalTime[select] = Integer.parseInt(keyboard.nextLine());

      System.out.print("일수업시간? ");
      dayTime[select] = Integer.parseInt(keyboard.nextLine());

      System.out.println();  // 빈 줄 출력
      System.out.println("계속 입력하시겠습니까?(Y/n)");
      String choose = keyboard.nextLine();
      if (!choose.equalsIgnoreCase("y") && !choose.equalsIgnoreCase("")) {
        break;
      }
    }
    keyboard.close();
    System.out.println(); // 빈 줄 출력

    // 출력할 내용
    if (nums != null) {
      int tmp = 0; // 인덱스로 사용하기 위한 정수 값 tmp를 선언 및 0으로 초기화
      while (tmp < length) {
        System.out.printf("번호: %d, ", nums[tmp]);
        System.out.printf("수업명: %s   , ", titles[tmp]);
        System.out.printf("기간: %s ~ %s, ", startDate[tmp], endDate[tmp]);
        System.out.printf("총수업시간: %d 시간\n", totalTime[tmp]);
        tmp++; // 인덱스 증가
      }
    }
  }
}
