/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App2 {
  public static void main(String[] args) {
    // 기본 출력
    System.out.println("번호: " + 1);
    System.out.println("이름: 홍길동");
    System.out.println("이메일: hong@test.com");
    System.out.println("암호: " + 1111);
    System.out.println("사진: hong.png");
    System.out.println("전화: 1111-2222");
    System.out.println("가입일: 2019-01-01");
    
    // 문자열의 형식을 정의하고 값을 대입해서 출력
    System.out.printf("번호: %d\n", 1);
    System.out.printf("이름: %s\n", "홍길동");
    System.out.printf("이메일: %s\n", "hong@test.com");
    System.out.printf("암호: %d\n", 1111);
    System.out.printf("사진: %s\n", "hong.png");
    System.out.printf("전화: %s\n", "1111-2222");
    System.out.printf("가입일: %s\n", "2019-01-01");
    
  }
}
