/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App2 {
  public static void main(String[] args) {
    // 키보드 입력 장치 선언
    java.util.Scanner keyboard = new java.util.Scanner(System.in);
    
    // 입력 받을 내용
    System.out.print("번호? ");
    int num = keyboard.nextInt();
    
    String tmp = keyboard.nextLine();  // LF값을 제거?
    
    System.out.print("이름? ");
    String name = keyboard.nextLine();
    
    System.out.print("이메일? ");
    String email = keyboard.nextLine();
    
    System.out.print("암호? ");
    String passWord = keyboard.nextLine();
    
    System.out.print("사진? ");
    String photo = keyboard.nextLine();
    
    System.out.print("전화? ");
    int firstPhoneNum = keyboard.nextInt();
    System.out.print(" - ");
    int secondPhoneNum = keyboard.nextInt();
    
    //현재 가입 날짜 생성
    java.util.Date today = new java.util.Date();
    
    System.out.println();  // 빈 줄 출력
    
    // 출력할 내용
    System.out.printf("번호: %d\n", num);
    System.out.printf("이름: %s\n", name);
    System.out.printf("이메일: %s\n", email);
    System.out.printf("암호: %s\n", passWord);
    System.out.printf("사진: %s\n", photo);
    System.out.printf("전화: %d - %d\n", firstPhoneNum, secondPhoneNum);
    
    // 가입 날짜 출력
    System.out.printf("가입일: %1$tY-%1$tm-%1$td\n", today);
    
  }
}
