/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.sql.Date;
import java.util.Scanner;

public class App3 {
  public static void main(String[] args) {
    Scanner keyboard = new Scanner(System.in);

    final int length = 10; // 배열 크기
    Board[] boards = new Board[length];
    
    // 입력할 내용
    int i = 0; // 배열의 index값 0 초기화
    while (i < length) {
      Board board = new Board();
      System.out.print("번호? ");
      board.num = Integer.parseInt(keyboard.nextLine());

      System.out.print("내용? ");
      board.content = keyboard.nextLine();

      // 생성 날짜 자동 입력
      board.createdDate = new Date(System.currentTimeMillis());

      // 조회수 초기화
      board.count = 0;

      boards[i] = board;
      i++; // index 값 증가

      // 계속 진행할 것인가?
      System.out.println("계속 입력 하시겠습니까?(Y/n) ");
      String answer = keyboard.nextLine();
      if (!answer.equalsIgnoreCase("y") && !answer.equalsIgnoreCase("")) {
        break;
      }
    }
    keyboard.close();
    System.out.println(); // 공백 출력

    // 출력할 내용
    i = 0; // 배열의 index값 0으로 초기화
    while (i < length) {
      System.out.printf("%d, %-20s, %s, %d\n", 
          boards[i].num, boards[i].content, boards[i].createdDate, boards[i].count);
      i++;
    }


  }
}
